CREATE OR REPLACE TABLE `user` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`isAdmin` BOOLEAN() DEFAULT false,
	`dateCreated` DATE() DEFAULT today(),
	`role` VARCHAR DEFAULT 'none',
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `student` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`ime` VARCHAR DEFAULT 'Dijak',
	`priimek` VARCHAR DEFAULT 'Dijak',
	`email` VARCHAR DEFAULT 'dijak@eviweb.org',
	`razred` INTEGER(),
	`emšo` BIGINT() DEFAULT 0,
	`spol` BOOLEAN(),
	`datumRojstva` DATE(),
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `teacher` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`ime` VARCHAR DEFAULT 'Učitelj',
	`priimek` VARCHAR DEFAULT 'Učitelj',
	`email` VARCHAR DEFAULT 'učitelj@eviweb.org',
	`emšo` BIGINT() DEFAULT 0,
	`datumRojstva` DATE() DEFAULT today(),
	`isRazrednik` BOOLEAN() DEFAULT false,
	`razred` INTEGER() DEFAULT 0,
	`plača` INTEGER(),
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `razred` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `parent` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`ime` VARCHAR DEFAULT 'Starš',
	`priimek` VARCHAR DEFAULT 'Starš',
	`email` VARCHAR,
	`otrok` INTEGER(),
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `grade` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`ocena` INTEGER() DEFAULT -1,
	`student` INTEGER(),
	`teacher` INTEGER(),
	`subject` INTEGER(),
	`date` DATE(),
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `subject` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`title` VARCHAR,
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `timetable` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`week` INTEGER(),
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `week` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`start` DATE(),
	`end` DATE(),
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `day` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`week` INTEGER(),
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `hour` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`dan` INTEGER(),
	`ucitelj` INTEGER(),
	`subject` INTEGER(),
	`opis` VARCHAR,
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `exam` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`subject` INTEGER(),
	`teacher` INTEGER(),
	`hour` INTEGER(),
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `absences` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`ura` INTEGER(),
	`student` INTEGER(),
	PRIMARY KEY(`id`)
);

ALTER TABLE `student`
ADD FOREIGN KEY(`id`) REFERENCES `user`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `teacher`
ADD FOREIGN KEY(`id`) REFERENCES `user`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `teacher`
ADD FOREIGN KEY(`razred`) REFERENCES `razred`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `student`
ADD FOREIGN KEY(`razred`) REFERENCES `razred`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `user`
ADD FOREIGN KEY(`id`) REFERENCES `parent`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `parent`
ADD FOREIGN KEY(`otrok`) REFERENCES `student`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `grade`
ADD FOREIGN KEY(`student`) REFERENCES `student`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `grade`
ADD FOREIGN KEY(`teacher`) REFERENCES `teacher`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `grade`
ADD FOREIGN KEY(`subject`) REFERENCES `subject`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `timetable`
ADD FOREIGN KEY(`week`) REFERENCES `week`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `day`
ADD FOREIGN KEY(`week`) REFERENCES `week`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `hour`
ADD FOREIGN KEY(`dan`) REFERENCES `day`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `hour`
ADD FOREIGN KEY(`ucitelj`) REFERENCES `teacher`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `hour`
ADD FOREIGN KEY(`subject`) REFERENCES `subject`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `exam`
ADD FOREIGN KEY(`subject`) REFERENCES `subject`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `exam`
ADD FOREIGN KEY(`teacher`) REFERENCES `teacher`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `exam`
ADD FOREIGN KEY(`hour`) REFERENCES `day`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `absences`
ADD FOREIGN KEY(`ura`) REFERENCES `hour`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `absences`
ADD FOREIGN KEY(`student`) REFERENCES `student`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;